# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16108spynRQQ6S182UbijnLoEsv1MS8aW

Load data
"""

import pandas as pd

df = pd.read_csv('properties_2025-09-26.csv')

df.count()

"""Clear missing data"""

df = df[df['size'].notna()]
df['update_date']=df['update_date'].fillna('unknown')
df.count()
df.info()

"""Normalize data, convert string to int and remove noise"""

import re

def normalize_bedrooms(value):
    if str(value).lower() == "studio":
        return 0
    try:
        return float(value)
    except:
        return None

def normalize_size(value):
  value = value.lower()
  value = value.replace("sqft", "")
  value = value.replace(",", "")  # <-- remove commas
  value = value.strip()

  try:
      return float(value)
  except:
      print(f"{value} cant be converted")
      return None


def normalize_price(value):
  match = re.search(r'RM([\d,]+)\s*/mo', value)

  if match:
      price = match.group(1).replace(',', '')  # remove comma
      try:
        return float(price)
      except:
        print(f"{value} cant be converted")
        return None
  else:
      print(f"{value} cant be converted")
      return None

df["bed"] = df["bed"].apply(normalize_bedrooms)
df["size"] = df["size"].apply(normalize_size)
df["price"] = df["price"].apply(normalize_price)
df["p/s"] = (df["price"]/df["size"]).round(2)

"""Remove noise

"""

df = df[(df["p/s"] >= 0.8) & (df["p/s"] <= 10)]
df.info()

"""Split address"""

def split_address(addr):
    if pd.isna(addr):
        return pd.Series([None, None, None])

    town, district, state, country= None, None, None, None
    parts = [p.strip() for p in addr.split(",")]  # split & strip spaces

    if len(parts) == 4:  # town, district, state, Malaysia
        town, district, state, country = parts
    elif len(parts) == 3:  # town, state, Malaysia (no district)
        town, state, country = parts
        district = town  # repeat town as district

    return pd.Series([town, district, state])

df[["town", "district", "state"]] = df["address"].apply(split_address)

df.head(5)

"""Normalize string obj"""

def normalize(value):
  value = str(value).strip().lower()
  return value

df["state"] = df["state"].apply(normalize)
df["town"] = df["town"].apply(normalize)
df["district"] = df["district"].apply(normalize)
df["type"] = df["type"].apply(normalize)

"""encode string to int (unnecessarry)

"""

import os

def encode(value, list):
  if isinstance(value, (int, float)):
      return float(value)
  value = str(value).strip().lower()

  if value in list:
    return float(list.index(value))
  else:
    list.append(value)
    return float(len(list) - 1)

def save_encoder_txt(filename='encoder_data.txt'):
    with open(filename, 'w') as f:
        f.write("# towns\n")
        for t in towns:
            f.write(t + "\n")
        f.write("\n# districts\n")
        for d in districts:
            f.write(d + "\n")
        f.write("\n# states\n")
        for s in states:
            f.write(s + "\n")
        f.write("\n# types\n")
        for ty in types:
            f.write(ty + "\n")
    print(f'Saved to {filename}')

def load_encoder_txt(filename='encoder_data.txt'):
    global towns, districts, states, types
    if not os.path.exists(filename):
        print(f'File not found ({filename}), starting fresh.')
        return

    current = None
    try:
      with open(filename, 'r') as f:
          for line in f:
              line = line.strip()

              if not line:
                  continue
              if line.startswith('#'):
                  current = line.lstrip('#').strip()
                  continue

              if current == 'towns': towns.append(line)
              elif current == 'districts': districts.append(line)
              elif current == 'states': states.append(line)
              elif current == 'types': types.append(line)

    except Exception as e:
        print(f'Error loading encoder data: {e}')

#declare list
towns = []
districts = []
states = []
types = []

#load
load_encoder_txt()

df["town"] = df["town"].apply(encode, list = towns)
df["district"] = df["district"].apply(encode, list = districts)
df["state"] = df["state"].apply(encode, list = states)
df["type"] = df["type"].apply(encode, list = types)

#save
save_encoder_txt()

df.to_excel("processed_data.xlsx", index=False)