// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRIMbkalFUbSsE0lYLzDSRYFtmPg1cRX8',
    appId: '1:337431716255:web:201d61e6436e0862e55daa',
    messagingSenderId: '337431716255',
    projectId: 'rentmanagement-91f4d',
    authDomain: 'rentmanagement-91f4d.firebaseapp.com',
    storageBucket: 'rentmanagement-91f4d.firebasestorage.app',
    measurementId: 'G-6TG3R2LS1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy-llhsMurJzZOxjIL9ioB2nYi66bU6yo',
    appId: '1:337431716255:android:7996fca3fd5dd3bfe55daa',
    messagingSenderId: '337431716255',
    projectId: 'rentmanagement-91f4d',
    storageBucket: 'rentmanagement-91f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYLchtBsCYqT-cHq8kvQMM3oK15CIKzY',
    appId: '1:337431716255:ios:01260fb161e90396e55daa',
    messagingSenderId: '337431716255',
    projectId: 'rentmanagement-91f4d',
    storageBucket: 'rentmanagement-91f4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYLchtBsCYqT-cHq8kvQMM3oK15CIKzY',
    appId: '1:337431716255:ios:01260fb161e90396e55daa',
    messagingSenderId: '337431716255',
    projectId: 'rentmanagement-91f4d',
    storageBucket: 'rentmanagement-91f4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRIMbkalFUbSsE0lYLzDSRYFtmPg1cRX8',
    appId: '1:337431716255:web:cd667a72106cfb0ce55daa',
    messagingSenderId: '337431716255',
    projectId: 'rentmanagement-91f4d',
    authDomain: 'rentmanagement-91f4d.firebaseapp.com',
    storageBucket: 'rentmanagement-91f4d.firebasestorage.app',
    measurementId: 'G-6BNJ362G4P',
  );
}
